#!/usr/bin/env python3
"""
This script performs the following:
1. Launches Firefox via Selenium for manual login to Pixiv.
2. Collects session cookies as you log in and saves them in a Netscape‑formatted file.
3. Creates an authenticated session and automatically retrieves your Pixiv user id.
4. Uses Pixiv’s AJAX endpoints to retrieve all your bookmarks (both public and private).
5. Downloads each bookmarked image concurrently, skipping any that already exist.
6. Saves the downloaded images in the "downloads" folder.
"""

import os
import time
import json
import concurrent.futures
import ssl
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
import httpx

# --- Selenium-based login and cookie extraction ---

def setup_driver():
    """Set up the Firefox webdriver (ensure geckodriver is in PATH)."""
    options = Options()
    options.headless = False  # So you can log in manually.
    driver = webdriver.Firefox(options=options)
    return driver

def login(driver):
    """
    Opens Pixiv's login page for manual login.
    After logging in and the page is fully loaded, press Enter in the terminal.
    """
    driver.get("https://accounts.pixiv.net/login")
    print("Please log in to Pixiv in the opened Firefox browser.")
    input("After logging in and ensuring the page has fully loaded, press Enter to continue...")

def save_cookies(driver, cookie_file):
    """
    Extract cookies from the Selenium session and save them in a Netscape‑formatted file.
    """
    cookies = driver.get_cookies()
    with open(cookie_file, "w") as f:
        # Write Netscape cookie file header.
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by Selenium\n")
        for cookie in cookies:
            domain = cookie.get("domain", "")
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.get("path", "/")
            secure = "TRUE" if cookie.get("secure", False) else "FALSE"
            expiry = cookie.get("expiry", 0)
            name = cookie.get("name", "")
            value = cookie.get("value", "")
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
    print(f"Cookies have been saved to {cookie_file}")

# --- Create an authenticated httpx Client with custom SSL context ---
def create_authenticated_session(cookie_file):
    """
    Create an httpx.Client with cookies loaded from the Netscape‑formatted file.
    Configures a custom SSL context to remove the OP_NO_TICKET flag and supports HTTP/2.
    Also sets headers to mimic the official Pixiv iOS App.
    """
    # Create a custom SSL context
    ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    ctx.load_default_certs()
    # Remove the OP_NO_TICKET flag to better mimic real browser behavior
    ctx.options &= ~ssl.OP_NO_TICKET
    # Enable ALPN for HTTP/2 support
    ctx.set_alpn_protocols(["h2", "http/1.1"])
    
    # Create an httpx client with HTTP/2 enabled and using our custom SSL context
    client = httpx.Client(http2=True, verify=ctx)
    
    # Load cookies from the cookie file
    with open(cookie_file, "r") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.strip().split("\t")
            if len(parts) >= 7:
                domain, flag, path, secure, expiry, name, value = parts[:7]
                client.cookies.set(name, value, domain=domain, path=path)
    
    # Set headers to mimic Pixiv's official iOS app
    client.headers.update({
        "User-Agent": "PixivIOSApp/7.13.3 (iOS 15.0; iPhone13,4)",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5"
    })
    return client

def get_user_id(client):
    """
    Retrieves your own Pixiv user id using the AJAX endpoint.
    Assumes you are already logged in.
    """
    url = "https://www.pixiv.net/ajax/user/self"
    response = client.get(url)
    response.raise_for_status()
    data = response.json()
    if data.get("error"):
        raise Exception(f"Error fetching user data: {data.get('message')}")
    user_id = data.get("body", {}).get("userId")
    if not user_id:
        raise Exception("Could not determine user id from Pixiv response.")
    print(f"Automatically retrieved user id: {user_id}")
    return user_id

def get_bookmarks(client, user_id, offset=0, limit=48, rest="show"):
    """
    Retrieve bookmarks from Pixiv for the given user via the AJAX endpoint.
    
    Returns a tuple (works, total) where:
      - works: a list of bookmark items.
      - total: total number of bookmarks available.
    """
    url = (f"https://www.pixiv.net/ajax/user/{user_id}/illusts/bookmarks"
           f"?tag=&offset={offset}&limit={limit}&rest={rest}")
    response = client.get(url)
    response.raise_for_status()
    data = response.json()
    if data.get("error"):
        raise Exception(f"Error fetching bookmarks: {data.get('message')}")
    body = data.get("body", {})
    total = body.get("total", 0)
    works = body.get("works", [])
    return works, total

def download_image(client, image_url, download_dir):
    """
    Downloads an image from image_url and saves it to download_dir.
    Uses the final segment of the URL as the filename.
    """
    filename = image_url.split("/")[-1]
    filepath = os.path.join(download_dir, filename)
    if os.path.exists(filepath):
        print(f"File already exists, skipping: {filepath}")
        return
    print(f"Downloading {image_url} -> {filepath}")
    response = client.get(image_url, stream=True)
    response.raise_for_status()
    with open(filepath, "wb") as f:
        for chunk in response.iter_bytes(chunk_size=8192):
            if chunk:
                f.write(chunk)
    print(f"Downloaded {filepath}")

def download_bookmarks(client, user_id, download_dir, max_workers=4, rest="show"):
    """
    Retrieves all bookmarks (public or private) for the given Pixiv user and downloads the images.
    """
    os.makedirs(download_dir, exist_ok=True)
    offset = 0
    limit = 48
    all_image_urls = []
    
    while True:
        works, total = get_bookmarks(client, user_id, offset, limit, rest)
        if not works:
            break
        for work in works:
            image_url = work.get("url")
            if image_url:
                all_image_urls.append(image_url)
        offset += limit
        if offset >= total:
            break
    print(f"Found {len(all_image_urls)} images to download for rest='{rest}'.")
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(download_image, client, url, download_dir)
                   for url in all_image_urls]
        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as exc:
                print("An image download generated an exception:", exc)

def main():
    cookie_file = "pixiv_cookies.txt"
    download_dir = "downloads"
    
    # Launch Firefox and perform manual login.
    driver = setup_driver()
    try:
        login(driver)
        time.sleep(5)  # Give extra time for cookies to settle.
        save_cookies(driver, cookie_file)
    finally:
        driver.quit()
    
    # Create an authenticated session using the collected cookies.
    client = create_authenticated_session(cookie_file)
    # Automatically retrieve the logged-in user's id.
    user_id = get_user_id(client)
    
    # Download both public and private bookmarks.
    print("Downloading public bookmarks...")
    download_bookmarks(client, user_id, download_dir, max_workers=4, rest="show")
    
    print("Downloading private bookmarks...")
    download_bookmarks(client, user_id, download_dir, max_workers=4, rest="hide")

if __name__ == "__main__":
    main()
