"""
Embedded site login inside the pywebview window (Windows / Edge WebView2).

FastAPI background threads call begin_embedded_login(); the user logs in on the
remote site in the same window, then chooses menu *SHUCK3R → Done logging in*
which saves cookies (including HttpOnly via WebView2) and returns to the app URL.

Set HAMSTER_EMBEDDED_LOGIN=0 to force the legacy Selenium login window instead.
"""

from __future__ import annotations

import logging
import os
import threading
from email.utils import parsedate_to_datetime
from typing import Any

logger = logging.getLogger(__name__)

_window: Any = None
_app_base_url: str = "http://127.0.0.1:8001/"
_cookie_target_path: str | None = None
_done_event = threading.Event()
_login_slot = threading.Lock()
_finish_guard = threading.Lock()


def configure(window: Any, app_base_url: str) -> None:
    """Call from the desktop launcher after create_window (before webview.start)."""
    global _window, _app_base_url
    _window = window
    base = app_base_url.rstrip("/")
    _app_base_url = base + "/"


def is_active() -> bool:
    return _window is not None


def embedded_login_env_enabled() -> bool:
    v = os.environ.get("HAMSTER_EMBEDDED_LOGIN", "").strip().lower()
    if v in ("0", "false", "no", "off"):
        return False
    return True


def simplecookie_list_to_netscape_file(cookies: list, path: str) -> None:
    """Write pywebview get_cookies() output (list of SimpleCookie) as Netscape jar."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by SHUCK3R (embedded WebView login)\n")
        for sc in cookies:
            for name, morsel in sc.items():
                domain = morsel.get("domain", "") or ""
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path_c = morsel.get("path", "/") or "/"
                secure = "TRUE" if morsel.get("secure", False) else "FALSE"
                expiry_unix = _morsel_expires_unix(morsel)
                f.write(f"{domain}\t{flag}\t{path_c}\t{secure}\t{expiry_unix}\t{name}\t{morsel.value}\n")
    logger.info("Saved %s cookie(s) to %s", len(cookies), path)


def _morsel_expires_unix(morsel: Any) -> int:
    raw = morsel.get("expires")
    if not raw:
        return 0
    if isinstance(raw, (int, float)):
        return int(raw)
    try:
        dt = parsedate_to_datetime(str(raw))
        if dt is None:
            return 0
        return int(dt.timestamp())
    except (TypeError, ValueError, OSError):
        return 0


def begin_embedded_login(login_url: str, cookie_file: str, *, timeout: float = 1800.0) -> None:
    """
    Navigate the WebView to login_url and block until the user completes the menu action
    or timeout. Writes cookies to cookie_file (Netscape format).
    """
    if not is_active():
        raise RuntimeError("Embedded login is not available (no WebView window).")
    if not embedded_login_env_enabled():
        raise RuntimeError("Embedded login disabled via HAMSTER_EMBEDDED_LOGIN.")

    if not _login_slot.acquire(blocking=False):
        raise RuntimeError(
            "Another embedded login is already in progress. Wait for it to finish before starting a second download."
        )

    global _cookie_target_path
    _done_event.clear()
    _cookie_target_path = cookie_file
    try:
        try:
            _window.set_title("Log in (embedded) — SHUCK3R")
        except Exception as e:
            logger.debug("set_title: %s", e)
        _window.load_url(login_url)
        logger.info(
            "Embedded login: open the site in the app window, sign in, then use menu "
            "'SHUCK3R → Done logging in — continue download'."
        )
        if _done_event.wait(timeout):
            return
        logger.warning("Embedded login timed out after %s s; returning to app.", timeout)
        try:
            _window.load_url(_app_base_url)
            _window.set_title("SHUCK3R")
        except Exception as e:
            logger.error("Could not restore app URL after login timeout: %s", e)
        raise TimeoutError(
            f"Embedded login timed out after {timeout:.0f} seconds. "
            "Use menu 'SHUCK3R → Done logging in — continue download' when finished."
        )
    finally:
        _cookie_target_path = None
        _login_slot.release()


def finish_embedded_login() -> None:
    """Menu handler: run cookie export off the GUI thread (avoids WinForms nested Invoke deadlocks)."""
    threading.Thread(target=_finish_embedded_login_impl, name="webview-login-finish", daemon=True).start()


def _finish_embedded_login_impl() -> None:
    with _finish_guard:
        path = _cookie_target_path
        if path is None:
            logger.debug("finish_embedded_login: no session in progress")
            return

        win = _window
        if win is None:
            _done_event.set()
            return

        try:
            cookies = win.get_cookies()
            simplecookie_list_to_netscape_file(cookies, path)
        except Exception as e:
            logger.exception("Failed to save cookies from WebView: %s", e)
        finally:
            try:
                win.load_url(_app_base_url)
                win.set_title("SHUCK3R")
            except Exception as e:
                logger.error("Could not return WebView to app after login: %s", e)
            _done_event.set()
