#!/usr/bin/env python3
"""
This script performs the following:
1. Launches Firefox via Selenium for manual login to Pornhub.
2. Extracts your session cookies into a Netscape‑formatted file.
3. Uses yt-dlp with --flat-playlist to extract individual video URLs
   from your favorites playlist.
4. Downloads each video in parallel with quality limited to 1080p maximum.
5. Saves the downloaded videos in the "downloads" folder.
6. Skips downloading any video if the expected output file already exists.
"""

import os
import time
import subprocess
import concurrent.futures
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

def setup_driver():
    """Set up the Firefox webdriver (make sure geckodriver is in PATH)."""
    options = Options()
    options.headless = False  # Set to False so you can log in manually.
    driver = webdriver.Firefox(options=options)
    return driver

def login(driver):
    """
    Opens Pornhub for manual login.
    After logging in and waiting for the page to fully load, press Enter in the terminal.
    """
    driver.get("https://www.pornhub.com")
    print("Please log in to Pornhub in the opened Firefox browser.")
    input("Once logged in and the page is fully loaded, press Enter to continue...")

def save_cookies(driver, cookie_file):
    """
    Extracts cookies from the Selenium session and saves them
    in the Netscape cookie file format (used by yt-dlp's --cookies option).
    """
    cookies = driver.get_cookies()
    with open(cookie_file, "w") as f:
        # Write the Netscape cookie file header.
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by Selenium\n")
        for cookie in cookies:
            domain = cookie.get("domain", "")
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.get("path", "/")
            secure = "TRUE" if cookie.get("secure", False) else "FALSE"
            expiry = cookie.get("expiry", 0)
            name = cookie.get("name", "")
            value = cookie.get("value", "")
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
    print(f"Cookies have been saved to {cookie_file}")

def extract_video_urls(cookie_file, playlist_url):
    """
    Uses yt-dlp with --flat-playlist to extract video URLs from the favorites playlist.
    Returns a list of URLs.
    """
    command = [
        "python", "-m", "yt_dlp",
        "--cookies", cookie_file,
        "--flat-playlist",
        "--print", "url",
        playlist_url
    ]
    print("Extracting video URLs with command:")
    print(" ".join(command))
    
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        print("Error extracting video URLs. Log output:")
        print(result.stderr)
        return []
    
    # Each line in the stdout output should be a video URL.
    urls = result.stdout.strip().splitlines()
    print(f"Extracted {len(urls)} video URLs.")
    return urls

def download_video(video_url, cookie_file):
    """
    Downloads a single video using yt-dlp.
    Before downloading, uses --get-filename to determine the expected output file name
    and skips the download if that file already exists.
    The output template saves videos in the "downloads" folder with quality limited to 1080p.
    """
    # Determine expected filename using yt-dlp's --get-filename.
    get_filename_cmd = [
        "python", "-m", "yt_dlp",
        "--cookies", cookie_file,
        "--get-filename",
        "-o", "downloads/%(title)s.%(ext)s",
        video_url
    ]
    try:
        result = subprocess.run(get_filename_cmd, capture_output=True, text=True, check=True)
        expected_filename = result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error getting filename for video {video_url}: {e}")
        expected_filename = None

    if expected_filename and os.path.exists(expected_filename):
        print(f"File already exists, skipping download: {expected_filename}")
        return

    command = [
        "python", "-m", "yt_dlp",
        "--cookies", cookie_file,
        "-o", "downloads/%(title)s.%(ext)s",
        # Format selection: best video (with height <= 1080) + best audio,
        # or best overall with height <= 1080.
        "-f", "bestvideo[height<=1080]+bestaudio/best[height<=1080]",
        video_url
    ]
    print(f"Downloading video: {video_url}")
    result = subprocess.run(command)
    if result.returncode != 0:
        print(f"Error downloading video: {video_url}")
    else:
        print(f"Successfully downloaded video: {video_url}")

def download_videos_parallel(cookie_file, playlist_url, max_workers=4):
    """
    Extracts video URLs from the playlist and downloads them in parallel.
    max_workers controls the number of parallel downloads.
    """
    video_urls = extract_video_urls(cookie_file, playlist_url)
    if not video_urls:
        print("No video URLs extracted. Exiting.")
        return

    # Ensure the output directory exists.
    os.makedirs("downloads", exist_ok=True)

    # Use ThreadPoolExecutor to download videos in parallel.
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(download_video, url, cookie_file) for url in video_urls]
        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as exc:
                print("A video download generated an exception:", exc)

def main():
    # The favorites URL for user burninglove999.
    playlist_url = "https://www.pornhub.com/users/burninglove999/videos/favorites"
    cookie_file = "logs/pornhub_cookies.txt"
    
    # Ensure logs directory exists
    os.makedirs("logs", exist_ok=True)
    
    driver = setup_driver()
    try:
        login(driver)
        time.sleep(5)  # Wait a few seconds to ensure cookies are fully set.
        save_cookies(driver, cookie_file)
    finally:
        driver.quit()
    
    # Download videos in parallel (adjust max_workers as needed).
    download_videos_parallel(cookie_file, playlist_url, max_workers=4)

if __name__ == "__main__":
    main()
