#!/usr/bin/env python3
"""
This script performs the following:
1. Launches Firefox via Selenium for manual login to Pornhub.
2. Extracts your session cookies into a Netscape‑formatted file.
3. Loads your favorites page, scrolls to trigger lazy load, clicks "Load More"
   until no more, and parses all video URLs from the HTML (yt-dlp returns 404 on the favorites URL).
4. Downloads each video in parallel with quality limited to 1080p maximum.
5. Saves the downloaded videos in the "downloads" folder.
6. Skips downloading any video if the expected output file already exists.
"""

import os
import re
import sys
import time
import subprocess
import concurrent.futures
from http.cookiejar import MozillaCookieJar
from urllib.parse import urljoin, urlparse, parse_qs
from selenium import webdriver
import requests
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from bs4 import BeautifulSoup

# Allow importing check_requirements from repo root when run as script
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.normpath(os.path.join(_SCRIPT_DIR, ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


def setup_driver():
    """Set up the Firefox webdriver (make sure geckodriver is in PATH)."""
    options = Options()
    options.headless = False  # Set to False so you can log in manually.
    driver = webdriver.Firefox(options=options)
    return driver

def login(driver):
    """
    Opens Pornhub for manual login.
    After logging in and waiting for the page to fully load, press Enter in the terminal.
    """
    driver.get("https://www.pornhub.com")
    print("Please log in to Pornhub in the opened Firefox browser.")
    input("Once logged in and the page is fully loaded, press Enter to continue...")

def save_cookies(driver, cookie_file):
    """
    Extracts cookies from the Selenium session and saves them
    in the Netscape cookie file format (used by yt-dlp's --cookies option).
    """
    cookies = driver.get_cookies()
    with open(cookie_file, "w") as f:
        # Write the Netscape cookie file header.
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by Selenium\n")
        for cookie in cookies:
            domain = cookie.get("domain", "")
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.get("path", "/")
            secure = "TRUE" if cookie.get("secure", False) else "FALSE"
            expiry = cookie.get("expiry", 0)
            name = cookie.get("name", "")
            value = cookie.get("value", "")
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
    print(f"Cookies have been saved to {cookie_file}")

def parse_video_links_pornhub(html, base_url="https://www.pornhub.com"):
    """
    Parse PornHub video links from HTML (view_video.php?viewkey=...).
    Used because yt-dlp --flat-playlist returns 404 on the favorites playlist URL.
    """
    soup = BeautifulSoup(html, "html.parser")
    video_links = []
    seen = set()
    for anchor in soup.select('a[href*="view_video"], a[href*="viewkey="]'):
        href = anchor.get("href")
        if not href or "viewkey=" not in href:
            continue
        video_url = urljoin(base_url, href)
        if video_url in seen:
            continue
        seen.add(video_url)
        video_links.append(video_url)
    return video_links


def scroll_to_bottom(driver, pause_time=2.0, max_scrolls=20):
    """
    Scroll to the bottom of the page to trigger lazy-loaded content (#moreData).
    Stops when scroll height stops increasing or after max_scrolls.
    """
    try:
        last_height = driver.execute_script("return document.body.scrollHeight")
        scrolls = 0
        while scrolls < max_scrolls:
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(pause_time)
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height
            scrolls += 1
    except Exception as e:
        print(f"Error during scroll: {e}")


def try_click_load_more(driver):
    """
    Click the 'Load More' button (#moreDataBtn) if present.
    Returns True if clicked, False if not found or not clickable.
    """
    try:
        btn = driver.find_element(By.ID, "moreDataBtn")
        if btn.is_displayed() and btn.is_enabled():
            driver.execute_script("arguments[0].click();", btn)
            return True
    except NoSuchElementException:
        pass
    except Exception as e:
        print(f"Error clicking Load More: {e}")
    return False


def extract_video_urls_selenium(driver, playlist_url, base_url="https://www.pornhub.com"):
    """
    Load the favorites page, scroll to trigger lazy load, click 'Load More'
    until no more, and extract all video URLs. Returns a list of full video page URLs.
    """
    print(f"Loading playlist page: {playlist_url}")
    driver.get(playlist_url)
    time.sleep(2)

    all_urls = set()
    load_more_attempts = 0
    max_load_more = 200  # safety limit
    clicked_load_more = False

    while load_more_attempts < max_load_more:
        # Scroll to bottom to trigger lazy load and reveal any "Load More" button
        scroll_to_bottom(driver, pause_time=2.0)
        time.sleep(1)

        html = driver.page_source
        new_urls = parse_video_links_pornhub(html, base_url)
        before = len(all_urls)
        all_urls.update(new_urls)
        added = len(all_urls) - before

        print(f"  Total video URLs so far: {len(all_urls)} (this pass: +{added})")

        # If we clicked Load More last time and got no new URLs, we're done
        if clicked_load_more and added == 0:
            print("  No new videos after last 'Load More'; finished.")
            break

        # Try to click "Load More" for the next batch
        clicked_load_more = try_click_load_more(driver)
        if not clicked_load_more:
            print("  No 'Load More' button (or no more pages).")
            break
        load_more_attempts += 1
        print(f"  Clicked 'Load More', waiting for new content...")
        time.sleep(3)

    result = list(all_urls)
    print(f"Extracted {len(result)} video URLs in total.")
    return result


def _session_with_cookies(cookie_file):
    """Load Netscape cookie file into a requests session."""
    session = requests.Session()
    jar = MozillaCookieJar(cookie_file)
    jar.load(ignore_discard=True, ignore_expires=True)
    session.cookies = jar
    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
    })
    return session


def _find_matching_bracket(html, start_pos, open_c, close_c):
    """Find the position of the matching close_c, skipping strings. start_pos is the index of open_c."""
    depth = 1
    i = start_pos + 1
    while i < len(html) and depth:
        if html[i] == '"':
            # Skip string (handle \")
            i += 1
            while i < len(html):
                if html[i] == "\\" and i + 1 < len(html):
                    i += 2
                    continue
                if html[i] == '"':
                    i += 1
                    break
                i += 1
            continue
        if html[i] == open_c:
            depth += 1
        elif html[i] == close_c:
            depth -= 1
        i += 1
    return i - 1 if depth == 0 else -1


def _extract_flashvars_block(html):
    """
    Find the flashvars_<id> = {...}; block as in ph-video.html (the specific actual part).
    Returns the inner {...} string or None.
    """
    # Pattern: var flashvars_<digits> = {
    m = re.search(r"var\s+flashvars_\d+\s*=\s*\{", html)
    if not m:
        return None
    start_brace = m.end() - 1  # index of the opening {
    end_brace = _find_matching_bracket(html, start_brace, "{", "}")
    if end_brace == -1:
        return None
    return html[start_brace : end_brace + 1]


def _extract_media_from_page(html, video_url):
    """
    Extract the best stream URL and video title from a PornHub video page HTML.
    Uses the same structure as website-code/ph-video.html: flashvars_<id>.mediaDefinitions.
    Prefer get_media (MP4) to avoid HLS segment 404s; fall back to HLS.
    Returns (media_url, format, title, viewkey) or None. format is "mp4" or "hls".
    """
    parsed = urlparse(video_url)
    qs = parse_qs(parsed.query)
    viewkey = qs.get("viewkey", [None])[0] or "unknown"

    # Restrict to the flashvars block (the actual part that contains mediaDefinitions in ph-video.html)
    flashvars = _extract_flashvars_block(html)
    if not flashvars:
        return None

    # Find "mediaDefinitions":[ inside the flashvars block
    md_start = flashvars.find('"mediaDefinitions":[')
    if md_start == -1:
        return None
    start = md_start + len('"mediaDefinitions":[')
    end_bracket = _find_matching_bracket(flashvars, start - 1, "[", "]")
    if end_bracket == -1:
        return None
    array_str = flashvars[start : end_bracket]

    # Parse each definition object: {"group":1,...,"format":"hls","videoUrl":"https:\/\/..."}
    definitions = []
    pos = 0
    while pos < len(array_str):
        obj_start = array_str.find("{", pos)
        if obj_start == -1:
            break
        end_brace = _find_matching_bracket(array_str, obj_start, "{", "}")
        if end_brace == -1:
            break
        block = array_str[obj_start : end_brace + 1]
        pos = end_brace + 1
        fmt = None
        url = None
        fm = re.search(r'"format"\s*:\s*"([^"]+)"', block)
        if fm:
            fmt = fm.group(1).strip()
        vm = re.search(r'"videoUrl"\s*:\s*"((?:[^"\\]|\\.)*)"', block)
        if vm:
            url = vm.group(1).replace("\\/", "/")
        if fmt and url:
            definitions.append((fmt, url))

    if not definitions:
        return None

    # Prefer get_media (MP4); then HLS
    media_url = None
    chosen_fmt = None
    for fmt, url in definitions:
        if "get_media" in url:
            media_url = url
            chosen_fmt = "mp4"
            break
    if not media_url and definitions:
        for fmt, url in definitions:
            if "m3u8" in url or fmt == "hls":
                media_url = url
                chosen_fmt = "hls"
                break
        if not media_url:
            media_url = definitions[0][1]
            chosen_fmt = definitions[0][0]

    # video_title is in the same flashvars block
    title = None
    tt = re.search(r'"video_title"\s*:\s*"((?:[^"\\]|\\.)*)"', flashvars)
    if tt:
        title = tt.group(1).replace("\\/", "/").replace('\\"', '"')
    if not title:
        title = viewkey

    return (media_url, chosen_fmt, title, viewkey)


def _sanitize_filename(s, max_len=180):
    """Replace invalid path chars and limit length."""
    s = re.sub(r'[<>:"/\\|?*]', "_", s)
    s = s.strip().strip(".") or "video"
    return s[:max_len] if len(s) > max_len else s


def _download_from_media_url(media_url, fmt, output_path, cookie_file):
    """Download from a direct stream URL (get_media or m3u8) using cookies."""
    if fmt == "mp4" or "get_media" in media_url:
        session = _session_with_cookies(cookie_file)
        try:
            r = session.get(media_url, stream=True, timeout=60)
            r.raise_for_status()
            with open(output_path, "wb") as f:
                for chunk in r.iter_content(chunk_size=1 << 20):
                    if chunk:
                        f.write(chunk)
            return True
        except Exception as e:
            print(f"  Request download failed: {e}")
            return False
    else:
        # HLS: use yt-dlp with the direct URL; merge to mp4 so output path is correct
        cmd = [
            sys.executable, "-m", "yt_dlp",
            "--cookies", cookie_file,
            "-o", output_path,
            "--merge-output-format", "mp4",
            "--no-warnings",
            media_url,
        ]
        r = subprocess.run(cmd)
        return r.returncode == 0


def _get_video_page_html(video_url, cookie_file, driver=None):
    """
    Get HTML of a PornHub video page (the same structure as website-code/ph-video.html).
    If driver is provided, use Selenium to open the URL and return page_source.
    Otherwise use requests with the cookie file.
    """
    if driver is not None:
        try:
            driver.get(video_url)
            time.sleep(2.5)
            return driver.page_source
        except Exception as e:
            print(f"Error loading video page in browser: {video_url} -> {e}")
            return None
    session = _session_with_cookies(cookie_file)
    try:
        r = session.get(video_url, timeout=30)
        r.raise_for_status()
        return r.text
    except Exception as e:
        print(f"Error fetching video page {video_url}: {e}")
        return None


def download_video(video_url, cookie_file, driver=None):
    """
    Opens the video page (with Selenium if driver given, else requests), finds the
    actual stream URL inside the page per website-code/ph-video.html (flashvars_.mediaDefinitions),
    then downloads from that URL. Skips if the output file already exists.
    """
    html = _get_video_page_html(video_url, cookie_file, driver=driver)
    if not html:
        return

    extracted = _extract_media_from_page(html, video_url)
    if not extracted:
        print(f"Could not extract media URL from page (no flashvars/mediaDefinitions): {video_url}")
        return

    media_url, fmt, title, viewkey = extracted
    safe_title = _sanitize_filename(title)
    output_path = os.path.join("downloads", f"{safe_title}_{viewkey}.mp4")

    if os.path.exists(output_path):
        print(f"File already exists, skipping: {output_path}")
        return

    print(f"Downloading: {title[:60]}{'...' if len(title) > 60 else ''} ({video_url})")
    ok = _download_from_media_url(media_url, fmt, output_path, cookie_file)
    if ok:
        print(f"Successfully downloaded: {output_path}")
    else:
        print(f"Error downloading video: {video_url}")


def download_videos_parallel(cookie_file, video_urls, max_workers=4, driver=None):
    """
    Download each video: open its page (with driver if given), extract the real
    stream URL from the page (mediaDefinitions in flashvars), then download.
    If driver is provided, pages are opened in the browser one by one (sequential).
    If not, pages are fetched with requests in parallel.
    """
    if not video_urls:
        print("No video URLs to download. Exiting.")
        return

    os.makedirs("downloads", exist_ok=True)

    if driver is not None:
        for url in video_urls:
            download_video(url, cookie_file, driver=driver)
        return

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(download_video, url, cookie_file, None) for url in video_urls]
        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as exc:
                print("A video download generated an exception:", exc)

def main():
    # The favorites URL for user burninglove999.
    playlist_url = "https://www.pornhub.com/users/burninglove999/videos/favorites"
    cookie_file = "logs/pornhub_cookies.txt"
    
    # Ensure logs directory exists
    os.makedirs("logs", exist_ok=True)

    # Ensure required package versions from requirements.txt; update if missing or outdated.
    from check_requirements import check_and_update_requirements
    req_path = os.path.join(_REPO_ROOT, "requirements.txt")
    if not check_and_update_requirements(req_path):
        print("Warning: some dependencies could not be updated. Continuing anyway.")

    driver = setup_driver()
    try:
        login(driver)
        time.sleep(5)  # Wait a few seconds to ensure cookies are fully set.
        save_cookies(driver, cookie_file)
        # Extract video URLs from the favorites page HTML (yt-dlp returns 404 on this URL).
        video_urls = extract_video_urls_selenium(driver, playlist_url)

        if not video_urls:
            print("No video URLs extracted. Exiting.")
            return

        # Open each video page in the browser (same as ph-video.html), find the real
        # stream URL inside the page (flashvars.mediaDefinitions), then download.
        print("Starting downloads: each video page will open in the browser to get the stream URL.")
        download_videos_parallel(cookie_file, video_urls, max_workers=1, driver=driver)
    finally:
        print("Closing browser.")
        driver.quit()

if __name__ == "__main__":
    main()
