#!/usr/bin/env python3
"""
This script performs the following:
1. Launches Firefox via Selenium for manual login to Pornhub.
2. Extracts your session cookies into a Netscape‑formatted file.
3. Loads your favorites page, scrolls to trigger lazy load, clicks "Load More"
   until no more, and parses all video URLs from the HTML (yt-dlp returns 404 on the favorites URL).
4. Downloads each video in parallel with quality limited to 1080p maximum.
5. Saves the downloaded videos in the "downloads" folder.
6. Skips downloading any video if the expected output file already exists.
"""

import os
import sys
import time
import subprocess
import concurrent.futures
from urllib.parse import urljoin
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from bs4 import BeautifulSoup

# Allow importing check_requirements from repo root when run as script
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.normpath(os.path.join(_SCRIPT_DIR, ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)


def setup_driver():
    """Set up the Firefox webdriver (make sure geckodriver is in PATH)."""
    options = Options()
    options.headless = False  # Set to False so you can log in manually.
    driver = webdriver.Firefox(options=options)
    return driver

def login(driver):
    """
    Opens Pornhub for manual login.
    After logging in and waiting for the page to fully load, press Enter in the terminal.
    """
    driver.get("https://www.pornhub.com")
    print("Please log in to Pornhub in the opened Firefox browser.")
    input("Once logged in and the page is fully loaded, press Enter to continue...")

def save_cookies(driver, cookie_file):
    """
    Extracts cookies from the Selenium session and saves them
    in the Netscape cookie file format (used by yt-dlp's --cookies option).
    """
    cookies = driver.get_cookies()
    with open(cookie_file, "w") as f:
        # Write the Netscape cookie file header.
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by Selenium\n")
        for cookie in cookies:
            domain = cookie.get("domain", "")
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.get("path", "/")
            secure = "TRUE" if cookie.get("secure", False) else "FALSE"
            expiry = cookie.get("expiry", 0)
            name = cookie.get("name", "")
            value = cookie.get("value", "")
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
    print(f"Cookies have been saved to {cookie_file}")

def parse_video_links_pornhub(html, base_url="https://www.pornhub.com"):
    """
    Parse PornHub video links from HTML (view_video.php?viewkey=...).
    Used because yt-dlp --flat-playlist returns 404 on the favorites playlist URL.
    """
    soup = BeautifulSoup(html, "html.parser")
    video_links = []
    seen = set()
    for anchor in soup.select('a[href*="view_video"], a[href*="viewkey="]'):
        href = anchor.get("href")
        if not href or "viewkey=" not in href:
            continue
        video_url = urljoin(base_url, href)
        if video_url in seen:
            continue
        seen.add(video_url)
        video_links.append(video_url)
    return video_links


def scroll_to_bottom(driver, pause_time=2.0, max_scrolls=20):
    """
    Scroll to the bottom of the page to trigger lazy-loaded content (#moreData).
    Stops when scroll height stops increasing or after max_scrolls.
    """
    try:
        last_height = driver.execute_script("return document.body.scrollHeight")
        scrolls = 0
        while scrolls < max_scrolls:
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(pause_time)
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height
            scrolls += 1
    except Exception as e:
        print(f"Error during scroll: {e}")


def try_click_load_more(driver):
    """
    Click the 'Load More' button (#moreDataBtn) if present.
    Returns True if clicked, False if not found or not clickable.
    """
    try:
        btn = driver.find_element(By.ID, "moreDataBtn")
        if btn.is_displayed() and btn.is_enabled():
            driver.execute_script("arguments[0].click();", btn)
            return True
    except NoSuchElementException:
        pass
    except Exception as e:
        print(f"Error clicking Load More: {e}")
    return False


def extract_video_urls_selenium(driver, playlist_url, base_url="https://www.pornhub.com"):
    """
    Load the favorites page, scroll to trigger lazy load, click 'Load More'
    until no more, and extract all video URLs. Returns a list of full video page URLs.
    """
    print(f"Loading playlist page: {playlist_url}")
    driver.get(playlist_url)
    time.sleep(2)

    all_urls = set()
    load_more_attempts = 0
    max_load_more = 200  # safety limit
    clicked_load_more = False

    while load_more_attempts < max_load_more:
        # Scroll to bottom to trigger lazy load and reveal any "Load More" button
        scroll_to_bottom(driver, pause_time=2.0)
        time.sleep(1)

        html = driver.page_source
        new_urls = parse_video_links_pornhub(html, base_url)
        before = len(all_urls)
        all_urls.update(new_urls)
        added = len(all_urls) - before

        print(f"  Total video URLs so far: {len(all_urls)} (this pass: +{added})")

        # If we clicked Load More last time and got no new URLs, we're done
        if clicked_load_more and added == 0:
            print("  No new videos after last 'Load More'; finished.")
            break

        # Try to click "Load More" for the next batch
        clicked_load_more = try_click_load_more(driver)
        if not clicked_load_more:
            print("  No 'Load More' button (or no more pages).")
            break
        load_more_attempts += 1
        print(f"  Clicked 'Load More', waiting for new content...")
        time.sleep(3)

    result = list(all_urls)
    print(f"Extracted {len(result)} video URLs in total.")
    return result

def download_video(video_url, cookie_file):
    """
    Downloads a single video using yt-dlp.
    Before downloading, uses --get-filename to determine the expected output file name
    and skips the download if that file already exists.
    The output template saves videos in the "downloads" folder with quality limited to 1080p.
    """
    # Determine expected filename using yt-dlp's --get-filename.
    get_filename_cmd = [
        "python", "-m", "yt_dlp",
        "--cookies", cookie_file,
        "--get-filename",
        "-o", "downloads/%(title)s.%(ext)s",
        video_url
    ]
    try:
        result = subprocess.run(get_filename_cmd, capture_output=True, text=True, check=True)
        expected_filename = result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error getting filename for video {video_url}: {e}")
        expected_filename = None

    if expected_filename and os.path.exists(expected_filename):
        print(f"File already exists, skipping download: {expected_filename}")
        return

    # Prefer non-HLS (MP4 / get_media) to avoid 404/412 on time-limited HLS segments.
    # Fall back to HLS if that's all that's available.
    format_spec = (
        "bestvideo[height<=1080][protocol!=m3u8_native][protocol!=m3u8]+bestaudio[protocol!=m3u8_native][protocol!=m3u8]/"
        "best[height<=1080][protocol!=m3u8_native][protocol!=m3u8]/"
        "bestvideo[height<=1080]+bestaudio/best[height<=1080]"
    )
    command = [
        "python", "-m", "yt_dlp",
        "--cookies", cookie_file,
        "-o", "downloads/%(title)s.%(ext)s",
        "-f", format_spec,
        video_url
    ]
    print(f"Downloading video: {video_url}")
    result = subprocess.run(command)
    if result.returncode != 0:
        print(f"Error downloading video: {video_url}")
    else:
        print(f"Successfully downloaded video: {video_url}")

def download_videos_parallel(cookie_file, video_urls, max_workers=4):
    """
    Downloads the given video URLs in parallel using yt-dlp and the cookie file.
    max_workers controls the number of parallel downloads.
    """
    if not video_urls:
        print("No video URLs to download. Exiting.")
        return

    # Ensure the output directory exists.
    os.makedirs("downloads", exist_ok=True)

    # Use ThreadPoolExecutor to download videos in parallel.
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(download_video, url, cookie_file) for url in video_urls]
        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as exc:
                print("A video download generated an exception:", exc)

def main():
    # The favorites URL for user burninglove999.
    playlist_url = "https://www.pornhub.com/users/burninglove999/videos/favorites"
    cookie_file = "logs/pornhub_cookies.txt"
    
    # Ensure logs directory exists
    os.makedirs("logs", exist_ok=True)

    # Ensure required package versions from requirements.txt; update if missing or outdated.
    from check_requirements import check_and_update_requirements
    req_path = os.path.join(_REPO_ROOT, "requirements.txt")
    if not check_and_update_requirements(req_path):
        print("Warning: some dependencies could not be updated. Continuing anyway.")

    driver = setup_driver()
    try:
        login(driver)
        time.sleep(5)  # Wait a few seconds to ensure cookies are fully set.
        save_cookies(driver, cookie_file)
        # Extract video URLs from the favorites page HTML (yt-dlp returns 404 on this URL).
        video_urls = extract_video_urls_selenium(driver, playlist_url)
    finally:
        print("Closing browser. Downloads will continue in the terminal.")
        input("Press Enter to close the browser and start downloading...")
        driver.quit()

    if not video_urls:
        print("No video URLs extracted. Exiting.")
        return

    # Download videos in parallel (adjust max_workers as needed).
    download_videos_parallel(cookie_file, video_urls, max_workers=4)

if __name__ == "__main__":
    main()
